# Generated by Django 5.1.1 on 2025-04-26 05:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Enter in UZS', max_digits=20)),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Enter in UZS', max_digits=20)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=10)),
                ('comments_count', models.DecimalField(decimal_places=0, default=Decimal('0'), editable=False, max_digits=10)),
                ('seen_count', models.PositiveBigIntegerField(blank=True, default=0)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('added_at', models.DateField(auto_now=True)),
                ('main_image', models.ImageField(upload_to='products/images/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter in UZS', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter in UZS', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feature_values', models.ManyToManyField(related_name='product_features_values', to='features.featurevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/images/%Y/%m/%d/')),
                ('ordering_number', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
