# Generated by Django 5.1.1 on 2025-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='owner_telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
