# Generated by Django 5.1.1 on 2025-05-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_long_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long_description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_uz',
        ),
    ]
