# Generated by Django 5.1.1 on 2025-06-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_long_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_room_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
