version: '3.9'

services:
  web:
    build:
      context: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
      - staticfiles_volume:/code/staticfiles
      - media_volume:/code/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - 8000
    networks:
      - backend
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    restart: always

  redis:
    image: redis:7
    networks:
      - backend
    restart: always

  celery:
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - backend
    restart: always

  celery-beat:
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - static_volume:/code/static
      - staticfiles_volume:/code/staticfiles
      - media_volume:/code/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    networks:
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jahongiranorboyev8@email.com --agree-tos --no-eff-email -d shinam-makon.uz
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:
  staticfiles_volume:
  media_volume:
  certbot-etc:
  certbot-var:

networks:
  backend:
    driver: bridge
