# Generated by Django 5.1.1 on 2025-04-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category.', max_length=255)),
                ('name_en', models.CharField(help_text='The name of the category.', max_length=255, null=True)),
                ('name_uz', models.CharField(help_text='The name of the category.', max_length=255, null=True)),
                ('name_ru', models.CharField(help_text='The name of the category.', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='An optional image representing the category.', null=True, upload_to='category/images/%Y/%m/%d/')),
                ('parent', models.ForeignKey(blank=True, help_text='The parent category for nested categories (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='category', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
