# Generated by Django 5.1.1 on 2025-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the about section (max 155 characters).', max_length=155)),
                ('title_en', models.CharField(help_text='Title of the about section (max 155 characters).', max_length=155, null=True)),
                ('title_uz', models.CharField(help_text='Title of the about section (max 155 characters).', max_length=155, null=True)),
                ('title_ru', models.CharField(help_text='Title of the about section (max 155 characters).', max_length=155, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description (max 255 characters).', max_length=255)),
                ('description_en', models.TextField(blank=True, help_text='Optional short description (max 255 characters).', max_length=255, null=True)),
                ('description_uz', models.TextField(blank=True, help_text='Optional short description (max 255 characters).', max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, help_text='Optional short description (max 255 characters).', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Upload path for the associated image.', upload_to='abouts/images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
    ]
