# Generated by Django 5.1.1 on 2025-04-26 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='UZB Number +998123456789', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number format. A valid number starts with +998 followed by 9 digits.', regex='^\\+998\\d{9}$')])),
                ('logo', models.ImageField(upload_to='general/logo/image/%Y/%m/%d/')),
                ('shipping_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'General',
                'verbose_name_plural': 'General',
            },
        ),
        migrations.CreateModel(
            name='GeneralSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to='social_links/icon/image/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('UZS', 'UZS')], max_length=10)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
