# Generated by Django 5.1.1 on 2025-05-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='address_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='address_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='address_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='text_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='text_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='text_uz',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
