# Generated by Django 5.1.1 on 2025-04-26 05:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, help_text='The rating given to the product (0-5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(help_text='The name of the commenter (if user is not logged in).', max_length=120)),
                ('email', models.EmailField(help_text='The email of the commenter.', max_length=254)),
                ('message', models.CharField(help_text='The content of the comment.', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the comment was created.')),
                ('product', models.ForeignKey(help_text='The product that this comment is related to.', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
